spring:
  application:
    name: BuyDobong

  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

server:
  port: 8080
  forward-headers-strategy: native

swagger:
  server-url: ${PUBLIC_BASE_URL}

jwt:
  secret: ${JWT_SECRET}
  access-ttl-ms: ${JWT_ACCESS_TTL_MS}
  phone-ttl-ms: ${JWT_PHONE_TTL_MS}

otp:
  ttl-seconds: ${OTP_TTL_SECONDS}
  key-prefix: ${OTP_KEY_PREFIX}

coolsms:
  apiKey: ${COOLSMS_API_KEY}
  apiSecret: ${COOLSMS_API_SECRET}
  senderNumber: ${COOLSMS_SENDER}
  endPoint: https://api.solapi.com

push:
  vapid:
    subject: "https://buy-dobong.vercel.app"
    public-key: ${PUSH_VAPID_PUBLIC_KEY}
    private-key: ${PUSH_VAPID_PRIVATE_KEY}
